version: 2
jobs:
  build:
    machine: true
    working_directory: ~/drone-frontend
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - run:
          name: create docker image
          command: docker build -t nicholasjackson/drone-frontend:latest
      - run:
          name: login to docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push docker image
          command: - docker push nicholasjackson/drone-frontend:latest
